CREATE TABLE bitacora (
    id_registro SERIAL PRIMARY KEY,
    fecha_hora TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    usuario VARCHAR(100) NOT NULL,
    operacion VARCHAR(255) NOT NULL
);

CREATE TABLE AGENCIA (
	CODIGO INT PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	DIRECCION VARCHAR(100),
	MUNICIPIO VARCHAR(50),
	TELEFONO VARCHAR(20),
	FECHA_APERTURA DATE
);

CREATE TABLE CARGO (
	ID_CARGO INT PRIMARY KEY,
	NOMBRE_CARGO VARCHAR(50),
	TURNO VARCHAR(30),
	ZONA VARCHAR(30),
	DESCRIPCION VARCHAR(30)
);

CREATE TABLE EMPLEADO (
	CEDULA_EMPLE VARCHAR(15) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	FECHA_INGRESO DATE,
	SALARIO DECIMAL(12, 2),
	CORREO VARCHAR(100) UNIQUE,
	ESTADO VARCHAR(20),
	CODIGO_AGENCIA INT NOT NULL,
	ID_CARGO INT NOT NULL,
	SUPERVISOR_CEDULA VARCHAR(15),
	CONSTRAINT FK_EMPLEADO_AGENCIA FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO),
	CONSTRAINT FK_EMPLEADO_CARGO FOREIGN KEY (ID_CARGO) REFERENCES CARGO (ID_CARGO),
	CONSTRAINT FK_EMPLEADO_SUPERVISOR FOREIGN KEY (SUPERVISOR_CEDULA) REFERENCES EMPLEADO (CEDULA_EMPLE)
);

CREATE TABLE ASOCIADO (
	CEDULA VARCHAR(15) PRIMARY KEY,
	NOMBRE VARCHAR(50) NOT NULL,
	APELLIDO VARCHAR(50) NOT NULL,
	TELEFONO VARCHAR(20),
	CORREO VARCHAR(100) UNIQUE,
	DIRECCION VARCHAR(100),
	MUNICIPIO VARCHAR(50),
	FECHA_AFILIACION DATE,
	FECHA_NACIMIENTO DATE,
	ESTADO VARCHAR(20),
	CONSTRAINT CHK_ASOCIADO_ESTADO CHECK (ESTADO IN ('activo', 'suspendido', 'retirado'))
);

CREATE TABLE FUNDADOR (
	CEDULA VARCHAR(15) PRIMARY KEY,
	NUMERO_ACTA VARCHAR(20),
	ANIO_RECONOCIMIENTO INT,
	BENEFICIOS TEXT,
	CONSTRAINT FK_FUNDADOR_ASOCIADO FOREIGN KEY (CEDULA) REFERENCES ASOCIADO (CEDULA)
);

CREATE TABLE BENEFICIARIO (
	DOCUMENTO VARCHAR(15) PRIMARY KEY,
	NOMBRE VARCHAR(80) NOT NULL,
	PARENTESCO VARCHAR(30),
	PORCENTAJE DECIMAL(5, 2),
	TELEFONO VARCHAR(20),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CONSTRAINT FK_BENEFICIARIO_ASOCIADO FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA),
	CONSTRAINT CHK_BENEFICIARIO_PARENTESCO CHECK (
		PARENTESCO IN (
			'cónyuge',
			'hijo/a',
			'padre',
			'madre',
			'hermano/a',
			'otro'
		)
	),
	CONSTRAINT CHK_BENEFICIARIO_PORCENTAJE CHECK (
		PORCENTAJE > 0
		AND PORCENTAJE <= 100
	)
);

CREATE TABLE CUENTA_AHORRO (
	NUMERO_CUENTA INT PRIMARY KEY,
	FECHA_APERTURA DATE,
	ESTADO VARCHAR(20),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CODIGO_AGENCIA INT NOT NULL,
	CONSTRAINT FK_CUENTA_ASOCIADO FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA),
	CONSTRAINT FK_CUENTA_AGENCIA FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO),
	CONSTRAINT CHK_CUENTA_ESTADO CHECK (ESTADO IN ('activa', 'inactiva', 'embargada'))
);

CREATE TABLE MOVIMIENTO (
	ID_TRANSACCION INT PRIMARY KEY,
	FECHA_HORA TIMESTAMP NOT NULL,
	TIPO VARCHAR(30) NOT NULL,
	VALOR DECIMAL(12, 2) NOT NULL,
	CANAL VARCHAR(30),
	NUMERO_CUENTA INT NOT NULL,
	CUENTA_DESTINO_ORIGEN INT,
	CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (NUMERO_CUENTA) REFERENCES CUENTA_AHORRO (NUMERO_CUENTA),
	CONSTRAINT FK_MOVIMIENTO_CUENTA_DESTINO FOREIGN KEY (CUENTA_DESTINO_ORIGEN) REFERENCES CUENTA_AHORRO (NUMERO_CUENTA),
	CONSTRAINT CHK_MOVIMIENTO_TIPO CHECK (
		TIPO IN (
			'depósito',
			'retiro',
			'transferencia entrante',
			'transferencia saliente'
		)
	),
	CONSTRAINT CHK_MOVIMIENTO_CANAL CHECK (
		CANAL IN (
			'presencial en agencia',
			'aplicación móvil',
			'cajero automático'
		)
	),
	CONSTRAINT CHK_MOVIMIENTO_VALOR CHECK (VALOR > 0)
);

CREATE TABLE CREDITO (
	NUMERO_RADICADO INT PRIMARY KEY,
	VALOR_SOLICITADO DECIMAL(12, 2),
	VALOR_APROBADO DECIMAL(12, 2),
	PLAZO INT,
	TASA_INTERES DECIMAL(5, 2),
	FECHA_APROBACION DATE,
	FECHA_PRIMER_VENCIMIENTO DATE,
	LINEA_CREDITO VARCHAR(30),
	ESTADO VARCHAR(20),
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	CODIGO_AGENCIA INT NOT NULL,
	CONSTRAINT FK_CREDITO_ASOCIADO FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA),
	CONSTRAINT FK_CREDITO_AGENCIA FOREIGN KEY (CODIGO_AGENCIA) REFERENCES AGENCIA (CODIGO),
	CONSTRAINT CHK_CREDITO_LINEA CHECK (
		LINEA_CREDITO IN (
			'libre inversión',
			'vivienda',
			'agropecuario',
			'educativo',
			'empresarial'
		)
	),
	CONSTRAINT CHK_CREDITO_ESTADO CHECK (
		ESTADO IN (
			'en estudio',
			'aprobado',
			'desembolsado',
			'al día',
			'en mora',
			'cancelado',
			'castigado'
		)
	)
);

CREATE TABLE PAGO_CUOTA (
	NUMERO_RADICADO INT NOT NULL,
	NUMERO_CUOTA INT NOT NULL,
	FECHA_PAGO DATE,
	VALOR_PAGADO DECIMAL(12, 2),
	ESTADO VARCHAR(20),
	CONSTRAINT PK_PAGO_CUOTA PRIMARY KEY (NUMERO_RADICADO, NUMERO_CUOTA),
	CONSTRAINT FK_PAGO_CREDITO FOREIGN KEY (NUMERO_RADICADO) REFERENCES CREDITO (NUMERO_RADICADO),
	CONSTRAINT CHK_PAGO_ESTADO CHECK (
		ESTADO IN ('a tiempo', 'pagado con mora', 'pendiente')
	)
);

CREATE TABLE ATIENDE (
	CEDULA_EMPLEADO VARCHAR(15) NOT NULL,
	CEDULA_ASOCIADO VARCHAR(15) NOT NULL,
	FECHA_ATENCION DATE,
	CONSTRAINT PK_ATIENDE PRIMARY KEY (CEDULA_EMPLEADO, CEDULA_ASOCIADO),
	CONSTRAINT FK_ATIENDE_EMPLEADO FOREIGN KEY (CEDULA_EMPLEADO) REFERENCES EMPLEADO (CEDULA_EMPLE),
	CONSTRAINT FK_ATIENDE_ASOCIADO FOREIGN KEY (CEDULA_ASOCIADO) REFERENCES ASOCIADO (CEDULA)
);

CREATE TABLE CODEUDOR (
	NUMERO_RADICADO INT NOT NULL,
	CEDULA_CODEUDOR VARCHAR(15) NOT NULL,
	FECHA_FIRMA DATE,
	CONSTRAINT PK_CODEUDOR PRIMARY KEY (NUMERO_RADICADO, CEDULA_CODEUDOR),
	CONSTRAINT FK_CODEUDOR_CREDITO FOREIGN KEY (NUMERO_RADICADO) REFERENCES CREDITO (NUMERO_RADICADO),
	CONSTRAINT FK_CODEUDOR_ASOCIADO FOREIGN KEY (CEDULA_CODEUDOR) REFERENCES ASOCIADO (CEDULA)
);
